CREATE DATABASE VEHICLE_API;

USE VEHICLE_API;

CREATE TABLE IF NOT EXISTS PERSONAS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    IDENTIFICACION VARCHAR(20) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50)    
);

INSERT INTO  PERSONAS(IDENTIFICACION, NOMBRE, APELLIDO)
VALUES
('10001','Maria', 'Gonzales'),
('10002', 'Carlos', 'Rodriguez'),
('10003', 'Juan', 'Sanchez'),
('10004', 'Angela', 'Ramirez'),
('10005', 'Martina', 'Ramirez'),
('10006', 'Pablo', 'Hernandez'),
('10007', 'Dario', 'Gonzales');

CREATE TABLE IF NOT EXISTS  TIPOS_REVISION(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

INSERT INTO TIPOS_REVISION(NOMBRE)
VALUES
('A'),
('B'),
('Externa'),
('Interna'),
('Completa');

CREATE TABLE IF NOT EXISTS  VEHICULO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    MARCA VARCHAR(50) NOT NULL,
    MODELO VARCHAR(10),
    PATENTE VARCHAR(20),
    AÑO INT,
    ID_PERSONA_DUEÑO INT,
    
    CONSTRAINT FK_VEHICULO_PERSONA 
    FOREIGN KEY (ID_PERSONA_DUEÑO) REFERENCES PERSONAS(ID)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

INSERT INTO VEHICULO(MARCA, MODELO, AÑO, ID_PERSONA_DUEÑO)
VALUES
('Mercedes', 'M1', 2019, 2),
('Audi', 'Q1', 2020, 1),
('Mazda', 'FX1', 2021, 3),
('Toyota', 'T1', 2022, 4);

CREATE TABLE IF NOT EXISTS  REVISION(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    APROBADO BOOL,
    OBSERVACIONES VARCHAR(500),
	FECHA_REVISION DATETIME,
    ID_PERSONA_ENCARGADO INT,
    ID_VEHICULO INT,
    
    CONSTRAINT FK_REVISION_ENCARGADO
    FOREIGN KEY (ID_PERSONA_ENCARGADO) REFERENCES PERSONAS(ID)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
    
    CONSTRAINT FK_REVISION_VEHICULO
    FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO(ID)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

INSERT INTO REVISION(APROBADO, OBSERVACIONES, FECHA_REVISION, ID_PERSONA_ENCARGADO, ID_VEHICULO)
VALUES
(true, 'Sin observaciones', '2021-08-10', 6, 1),
(false, 'Es necesario cambiar el motor', '2021-09-15', 7, 3),
(true, 'Sin observaciones', '2021-12-05', 6, 2),
(false, 'Es necesario cambiar las camaras', '2021-12-20', 7, 4);

CREATE TABLE IF NOT EXISTS  ESTADOS_INSPECCION(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50)
);

INSERT INTO ESTADOS_INSPECCION(NOMBRE)
VALUES
('Pendiente'),
('En curso'),
('Terminado');

CREATE TABLE IF NOT EXISTS  INSPECCION(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    OBSERVACIONES VARCHAR(500),
    ID_ESTADO INT,
    ID_TIPO_REVISION INT,
    ID_PERSONA_ENCARGADO INT,
    
    CONSTRAINT FK_INSPECCION_ESTADO
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS_INSPECCION(ID)
    ON UPDATE CASCADE ON DELETE SET NULL,
    
    CONSTRAINT FK_INSPECCION_TIPO_REVISION
    FOREIGN KEY (ID_TIPO_REVISION) REFERENCES TIPOS_REVISION(ID)
    ON UPDATE CASCADE ON DELETE SET NULL,
    
    CONSTRAINT FK_INSPECCION_ID_ENCARGADO
    FOREIGN KEY (ID_PERSONA_ENCARGADO) REFERENCES PERSONAS(ID)
    ON UPDATE CASCADE ON DELETE SET NULL
);




